import argparse
from datetime import datetime
import os
import re

from topology_generator import simulation_generate_topology
from routes_generator import simulation_generate_routes

def simulation_initialisation(simulation_name):
    """Create or Overwrite the simulation file, write Doxygen headers, includes,

    and define the log component.
    """
    log_component_name = os.path.basename(simulation_name).replace(".cc", "")
    log_component_name = log_component_name.capitalize()

    # Convert to kebab-case for the physical filename (e.g., TrafficSimulation -> traffic-simulation)
    file_base_name = re.sub(r"(?<!^)(?=[A-Z])", "-", log_component_name)
    file_base_name = re.sub(r"[_\s]+", "-", file_base_name).lower()

    simulation_path = f"scratch/{file_base_name}.cc"
    current_date = datetime.now().strftime("%Y-%m-%d")

    # Ensure the destination directory exists
    os.makedirs("scratch", exist_ok=True)

    # Write global scope headers
    with open(simulation_path, "w", encoding="utf-8") as simulation_file:
        # Doxygen Header
        simulation_file.write("/**\n")
        simulation_file.write(f" * @file {file_base_name}.cc\n")
        simulation_file.write(f" * @date {current_date}\n")
        simulation_file.write(" *\n")
        simulation_file.write(
            " * @brief This file was automatically generated by the Python NS-3 simulation generator.\n"
        )
        simulation_file.write(" */\n\n")

        # NS-3 Mandatory Modules
        simulation_file.write('#include "ns3/core-module.h"\n')
        simulation_file.write('#include "ns3/network-module.h"\n')
        simulation_file.write('#include "ns3/tsn-module.h"\n')
        simulation_file.write('#include "ns3/ethernet-module.h"\n')
        simulation_file.write('#include "ns3/traffic-generator-module.h"\n\n')

        # Global Scope Configuration
        simulation_file.write("using namespace ns3;\n\n")
        simulation_file.write(
            f'NS_LOG_COMPONENT_DEFINE ("{log_component_name}");\n\n'
        )

    print(f"File successfully initialised at: {simulation_path}")

    # Return metadata to keep downstream functions synchronized
    return {"path": simulation_path, "component": log_component_name}


def simulation_start_main(meta, enable_tracing=True):
    """Open the main function scope, parse CLI arguments, and enable logging triggers."""
    simulation_path = meta["path"]
    component_name = meta["component"]

    with open(simulation_path, "a", encoding="utf-8") as file:
        file.write("int main(int argc, char* argv[])\n{\n")

        if enable_tracing:
            file.write("  // --- Logging and Tracing Configuration ---\n")
            file.write(
                f'  LogComponentEnable("{component_name}", LOG_LEVEL_INFO);\n\n'
            )
        else:
            file.write("  // Logging disabled via generator configuration\n\n")


def simulation_close_main(meta):
    """Append the mandatory NS-3 execution loop and close the main function scope."""
    simulation_path = meta["path"]

    with open(simulation_path, "a", encoding="utf-8") as file:
        file.write("\n  // --- Simulation Execution ---\n")
        file.write("  Simulator::Run();\n")
        file.write("  Simulator::Destroy();\n\n")
        file.write("  return 0;\n")
        file.write("}\n")

    print(f"File successfully closed and finalized.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="NS-3 Simulation Generator (Core Scaffold Architecture)"
    )

    parser.add_argument(
        "-n",
        "--name",
        type=str,
        required=True,
        help="Name of the simulation scenario (e.g., TrafficSimulationTest)",
    )

    parser.add_argument(
        "-c",
        "--config",
        type=str,
        nargs="+",
        required=True,
        help="List of JSON configuration files (e.g., topology.json routes.json)",
    )

    args = parser.parse_args()

    print(f"Executing generation flow for scenario: {args.name}")

    # Create file and inject components definitions
    meta_data = simulation_initialisation(args.name)

    # Start the execution block and telemetry options
    simulation_start_main(meta_data, enable_tracing=True)

    # Call the imported topology generator to inject the JSON network
    if len(args.config) >= 1:
        simulation_generate_topology(meta_data, args.config[0])

    # Call the imported routes generator to inject the JSON routes
    if len(args.config) >= 2:
        simulation_generate_routes(meta_data, args.config[1])
        
    # Finalize the runtime lifecycle
    simulation_close_main(meta_data)

    print("Pipeline sequence executed successfully. Ready for compilation.")